name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master"]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: chmod +x docker-build.sh
    - name: Rust-Build
      run: cargo build --verbose
    - name: Docker-Build
      run: ./docker-build.sh

